@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Aug 26 21:18:22 -0400 2025
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim dp_helper_fsm_tb_behav -key {Behavioral:sim_1:Functional:dp_helper_fsm_tb} -tclbatch dp_helper_fsm_tb.tcl -log simulate.log"
call xsim  dp_helper_fsm_tb_behav -key {Behavioral:sim_1:Functional:dp_helper_fsm_tb} -tclbatch dp_helper_fsm_tb.tcl -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
